app.cors.allowed-origins=https://app.afterit.ee
app.jwt.superSecretKey=Ivj316XdWR20QXvJTAndeUsOUiiPWN1m0D525BJL_6Wiv9prllrerjkn3VsEVUhLsy-v9rnwU2a-MEin_3lNeg
spring.datasource.url=jdbc:postgresql://budgetmaster-prod.c52604042vn5.eu-north-1.rds.amazonaws.com/postgres
spring.datasource.username=budgMaster
spring.datasource.password=3.g3yy!QhGF_nvug2Wbq
server.port=5000