app.cors.allowed-origins=http://localhost:5173
app.jwt.superSecretKey=Y29tcG9zaXRpb25lYXJseXNpY2tkYW5jZWZpZ2h0aW5nYmVjb21pbmdkb25lcmFwaWQ
spring.datasource.url=jdbc:postgresql://localhost:5432/budget_master
spring.datasource.username=postgres
spring.datasource.password=root